dataset_name: lstm_v1
preprocessed_root: data/preprocessed
station_dir: data/preprocessed/station
output_dir: data/lstm_processed

sources:
  - name: 2024_april_june
    path: data/preprocessed/2024_april_june
  - name: 2025
    path: data/preprocessed/2025

horizon: 1
target_columns:
  - rental_count
  - return_count

window:
  mode: explicit_offsets
  offsets:
    - -8
    - -7
    - -6
    - -5
    - -4
    - -3
    - -2
    - -1

train_split_name: train
scaling_chunk_size: 512

splits:
  train:
    - source: 2025
      start: 2025-01-01
      end: 2025-09-30

  val:
    - source: 2025
      start: 2025-10-01
      end: 2025-10-31

  test_2025_winter:
    - source: 2025
      start: 2025-11-01
      end: 2025-12-31

  test_2024_april_june:
    - source: 2024_april_june
      start: 2024-04-01
      end: 2024-06-30
